name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # define PYTHONPATH para todo o job (github.workspace = repo root)
      PYTHONPATH: ${{ github.workspace }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug info
      run: |
        echo "Working dir: $(pwd)"
        echo "List files:"
        ls -la
        echo "PYTHONPATH: $PYTHONPATH"
        python -c "import sys; print('sys.path first entries:', sys.path[:3])"

    - name: Run tests
      run: |
        pytest -q
